---
- hosts: localhost
  connection: local
  
  - name: "nb_node_to_create"
    prompt: "Nb of node to create"
    default: 3
  
  tasks:
  - name: Create a started container
    lxd_container:
      name: node-{{ item }}
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        alias: debian/9
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
    with_sequence: count={{ nb_node_to_create }}
  
  - name: Create hosts file from template file
    template:
      src: ../tmpl-file/hosts.j2
      dest: ../inventory/hosts
    
  - name: Refresh inventory to ensure new instaces exist in inventory
    meta: refresh_inventory

- hosts: lxd_container_group
  gather_facts: False
  tasks:
    - name: Install python
      raw: apt-get install -y python

- hosts: lxd_container_group
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
