---
- hosts: localhost
  connection: local
  
  vars_prompt:
  - name: "nb_node_to_create"
    prompt: "Nb of node to create"
    default: 3

  tasks:
  - name: Create started container
    lxd_container:
      name: node-{{ item }}
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: simplestreams
        #alias: centos/7
        #protocol: lxd
        alias: ubuntu/xenial
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
    with_sequence: count={{ nb_node_to_create }}
  
  - name: Create hosts file from template file
    template:
      src: ../tmpl-file/hosts.j2
      dest: ../inventory/hosts
    
  - name: Refresh inventory to ensure new instaces exist in inventory
    meta: refresh_inventory

- hosts: lxd_container_group
  gather_facts: False
  tasks:
  - name: Install python - Debian family
    raw: apt-get install -y python
    ignore_errors: true

  - name: Install python - RedHat family
    raw: yum install -y python
    ignore_errors: true

- hosts: lxd_container_group
  tasks:
  - name: Update all packages to the latest version - Debian family
    apt:
      upgrade: dist
    when: ansible_os_family == "Debian"

  - name: Update all packages to the latest version - RedHat family
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"